
    $(function(){
        $("#button1").click(function(){
        $("#slide1").fadeIn();
        $("#slide2").hide();
    })
    $("#button2").click(function(){
        $("#slide2").fadeIn();
        $("#slide1").hide();
    })
    });

    $(function(){
        $("#li1").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_1").fadeIn();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_6").hide();
            $("#sec6_7").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li2").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_2").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_6").hide();
            $("#sec6_7").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li3").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_3").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_6").hide();
            $("#sec6_7").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li4").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_4").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_5").hide();
            $("#sec6_6").hide();
            $("#sec6_7").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li5").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_5").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_6").hide();
            $("#sec6_7").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li6").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_6").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_7").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li7").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_7").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_6").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li8").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_8").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_7").hide();
            $("#sec6_6").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li9").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_9").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_7").hide();
            $("#sec6_6").hide();
            $("#sec6_8").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li10").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_10").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_7").hide();
            $("#sec6_6").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_11").hide();
            $("#sec6_12").hide();
        })
        $("#li11").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_11").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_7").hide();
            $("#sec6_6").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_12").hide();
        })
        $("#li12").click(function(){
            $('#sec6 li').removeClass('active');
            $(this).addClass('active');
            $("#sec6_12").fadeIn();
            $("#sec6_1").hide();
            $("#sec6_2").hide();
            $("#sec6_3").hide();
            $("#sec6_4").hide();
            $("#sec6_5").hide();
            $("#sec6_7").hide();
            $("#sec6_6").hide();
            $("#sec6_8").hide();
            $("#sec6_9").hide();
            $("#sec6_10").hide();
            $("#sec6_11").hide();
        })
    });